title: "My Multilingual Jekyll Site"
description: "My personal webpage with multilingual support using Jekyll"

baseurl: ""
url: "https://martinnecpal.github.io"

# buld settingsfor GitHub Pages
markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Multilingual settings
languages: ["en", "sk"]  # Add more languages if needed
default_lang: "en"

defaults:
  - scope:
      path: "en"
    values:
      lang: "en"

  - scope:
      path: "sk"
    values:
      lang: "sk"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - package.json
  - package-lock.json